services:
  # NextJS application
  next_app:
    container_name: ${COMPOSE_PROJECT_NAME}_next_app
    env_file: .env
    build:
      context: ./next-app
      dockerfile: docker/dev.dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        # prefixed "NEXT_PUBLIC" give read access to nodejs and browser
        NEXT_PUBLIC_APP_HOST_DOMAIN: ${NEXT_APP_HOST_DOMAIN}
        NEXT_PUBLIC_APP_EXTERNAL_URL: ${NEXT_APP_EXTERNAL_URL}
        # other variables give access to nodejs only
        NEXT_APP_HOST_HTTP_PORT: ${NEXT_APP_HOST_HTTP_PORT}
        NEXT_APP_HOST_HTTPS_PORT: ${NEXT_APP_HOST_HTTPS_PORT}
    volumes:
      - ${NEXT_APP_DATA_DIR:-./next-app}/src:/app/src
      - ${NEXT_APP_DATA_DIR:-./next-app}/public:/app/public
      - ${NEXT_APP_DATA_DIR:-./next-app}/.next:/app/.next
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - next_app_network

  # Database
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: docker.io/bitnami/mariadb:${MARIADB_VERSION:-latest}
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PORT: ${MARIADB_PORT:-3306}
      ALLOW_EMPTY_PASSWORD: no
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - next_app_network

  # Nginx webserver
  webserver:
    depends_on:
      - next_app
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NEXT_APP_DATA_DIR:-./next-app}:/var/www/html
      - ./next-app/nginx-conf:/etc/nginx/conf.d
    networks:
      - next_app_network

# Volumes
volumes:
  mariadb_data:

# Networks
networks:
  next_app_network:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}_network"