import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface AppOptions {
  externalUrl?: string
}

const appOptions: AppOptions = {
  // externalUrl: process.env.NEXT_APP_EXTERNAL_URL
  externalUrl: process.env.NEXT_PUBLIC_APP_EXTERNAL_URL
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>Alpcloud application production enabled - 01/04/2025 - 14h32</h1>
        <p>url: {appOptions.externalUrl}</p>
        {children}
      </body>
    </html>
  );
}
